// flutter
export 'package:flutter/material.dart';
export 'dart:io' hide HeaderValue, Socket;
export 'dart:async';
export 'package:flutter/services.dart';
export 'dart:convert';
export 'package:flutter/foundation.dart';
export 'package:flutter/gestures.dart';
export 'dart:ui' show ImageFilter;

// plugins
export 'package:get/get.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:permission_handler/permission_handler.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:smooth_page_indicator/smooth_page_indicator.dart';
export 'package:dropdown_button2/dropdown_button2.dart';
export 'package:carousel_slider/carousel_slider.dart';
export 'package:image_cropper/image_cropper.dart';
export 'package:image_picker/image_picker.dart';
export 'package:fancy_shimmer_image/fancy_shimmer_image.dart';
export 'package:http_parser/http_parser.dart';
export 'package:qr_flutter/qr_flutter.dart';
export 'package:mobile_scanner/mobile_scanner.dart';
export 'package:razorpay_flutter/razorpay_flutter.dart';
export 'package:slider_button/slider_button.dart';
export 'package:agora_rtc_engine/agora_rtc_engine.dart';
export 'package:flutter_callkit_incoming/flutter_callkit_incoming.dart';
export 'package:flutter_callkit_incoming/entities/entities.dart';
export 'package:uuid/uuid.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_messaging/firebase_messaging.dart';
export 'package:flutter_local_notifications/flutter_local_notifications.dart' hide NotificationVisibility;
export 'package:intl/intl.dart' hide TextDirection;
export 'package:path_provider/path_provider.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:socket_io_client/socket_io_client.dart' ;
export 'package:simple_html_css/simple_html_css.dart';
export 'package:audioplayers/audioplayers.dart';
export 'package:scan_me_plus/utils/simple_ripple_animation.dart';

// export 'package:flutter_overlay_window/flutter_overlay_window.dart';

// main
export 'package:scan_me_plus/main.dart';
export 'package:scan_me_plus/notification/notification_service.dart';

// routes
export 'package:scan_me_plus/route/app_routes.dart';
export 'package:scan_me_plus/route/app_pages.dart';

// network
export 'package:scan_me_plus/network/api_urls.dart';
export 'package:scan_me_plus/network/remote_services.dart';
export 'package:scan_me_plus/network/post_requests.dart';
export 'package:scan_me_plus/network/get_requests.dart';
export 'package:scan_me_plus/network/delete_request.dart';
export 'package:scan_me_plus/network/put_requests.dart';

// dialog
export 'package:scan_me_plus/views/dialogs/common_alert_dialog.dart';

// config
export 'package:scan_me_plus/config/app_colors.dart';
export 'package:scan_me_plus/config/app_theme.dart';
export 'package:scan_me_plus/config/local_strings.dart';

// const
export 'package:scan_me_plus/const/app_const.dart';
export 'package:scan_me_plus/const/app_images.dart';
export 'package:scan_me_plus/const/app_formatters.dart';

// utils
export 'package:scan_me_plus/utils/preference_manager.dart';
export 'package:scan_me_plus/utils/helpers.dart';
export 'package:scan_me_plus/utils/internet_connection.dart';
export 'package:scan_me_plus/utils/permission_handler.dart';
export 'package:scan_me_plus/utils/app_alerts.dart';
export 'package:scan_me_plus/utils/validator.dart';
export 'package:scan_me_plus/utils/image_picker.dart';
export 'package:scan_me_plus/utils/socket_helper.dart';
export 'package:scan_me_plus/utils/double_back_press.dart';

// models
export 'package:scan_me_plus/models/device_info/device_model.dart';
export 'package:scan_me_plus/models/common_response_model.dart';
export 'package:scan_me_plus/models/base_response_model.dart';
export 'package:scan_me_plus/models/authentication/check_mail_res_model.dart';
export 'package:scan_me_plus/models/authentication/req_otp_res_model.dart';
export 'package:scan_me_plus/models/authentication/states_response_model.dart';
export 'package:scan_me_plus/models/authentication/login_response_model.dart';
export 'package:scan_me_plus/models/vehicle/vehicles_brand_response_model.dart';
export 'package:scan_me_plus/models/vehicle/my_vehicles_response_model.dart';
export 'package:scan_me_plus/models/upload_file_response_model.dart';
export 'package:scan_me_plus/models/vehicle/searched_vehicle_response_model.dart';
export 'package:scan_me_plus/models/membership/membership_plan_response_model.dart';
export 'package:scan_me_plus/models/vehicle/add_vehicle_response_model.dart';
export 'package:scan_me_plus/models/call/start_call_response_model.dart';
export 'package:scan_me_plus/models/call/call_history_response_model.dart';
export 'package:scan_me_plus/models/call/call_detail_response_model.dart';
export 'package:scan_me_plus/models/emergencyAlert/emergency_alert_response_model.dart';
export 'package:scan_me_plus/models/shipping_address/shipping_address_response_model.dart';
export 'package:scan_me_plus/models/notification_model/notifications_response_model.dart';
export 'package:scan_me_plus/models/notification_model/alert_notification_response_model.dart';
export 'package:scan_me_plus/models/call/blocked_user_response_model.dart';
export 'package:scan_me_plus/models/shipping_address/add_shipping_address_response_model.dart';
export 'package:scan_me_plus/models/vehicle/replacement_request_model.dart';
export 'package:scan_me_plus/models/membership/upgrade_subscription_response_model.dart';
export 'package:scan_me_plus/models/membership/invoice_detail_response_model.dart';
export 'package:scan_me_plus/models/banner_response_model.dart';
export 'package:scan_me_plus/models/notification_model/new_notification_status_response_model.dart';
export 'package:scan_me_plus/models/static_pages/static_page_response_model.dart';

// widgets
export 'package:scan_me_plus/views/widgets/custom_button.dart';
export 'package:scan_me_plus/views/widgets/ink_well_widget.dart';
export 'package:scan_me_plus/views/widgets/custom_text_field.dart';
export 'package:scan_me_plus/views/widgets/custom_scaffold.dart';
export 'package:scan_me_plus/views/widgets/custom_app_bar.dart';
export 'package:scan_me_plus/views/widgets/custom_dropdown.dart';
export 'package:scan_me_plus/views/widgets/vehicle_list_view.dart';
export 'package:scan_me_plus/views/widgets/empty_state_widget.dart';
export 'package:scan_me_plus/views/widgets/common_progress_bar.dart';
export 'package:scan_me_plus/views/widgets/network_image.dart';

// bottomSheets
export 'package:scan_me_plus/views/bottom_sheets/message_bottom_sheet_content.dart';
export 'package:scan_me_plus/views/bottom_sheets/common_bottom_sheet_background.dart';
export 'package:scan_me_plus/views/bottom_sheets/vehicle_detail_bottom_sheet.dart';
export 'package:scan_me_plus/views/bottom_sheets/send_feedback_bottom_sheet.dart';
export 'package:scan_me_plus/views/bottom_sheets/emergency_alert_bottom_sheet.dart';
export 'package:scan_me_plus/views/bottom_sheets/pick_image_options_bottom_sheet.dart';
export 'package:scan_me_plus/models/membership/subscription_payment_response_model.dart';

// pages
export 'package:scan_me_plus/views/pages/splash/splash_screen.dart';
export 'package:scan_me_plus/views/pages/on_boarding/on_boarding_screen.dart';
export 'package:scan_me_plus/views/pages/login/login_screen.dart';
export 'package:scan_me_plus/views/pages/otp_verification/otp_verification_screen.dart';
export 'package:scan_me_plus/views/pages/add_profile_detail/add_profile_detail_screen.dart';
export 'package:scan_me_plus/views/pages/home/main_screen.dart';
export 'package:scan_me_plus/views/pages/home/home_screen.dart';
export 'package:scan_me_plus/views/pages/call/call_history_screen.dart';
export 'package:scan_me_plus/views/pages/plans/my_plans_screen.dart';
export 'package:scan_me_plus/views/pages/profile/my_profile_screen.dart';
export 'package:scan_me_plus/views/pages/add_vehicle_detail/choose_vehicle_brand_screen.dart';
export 'package:scan_me_plus/views/pages/add_vehicle_detail/choose_vehicle_model_screen.dart';
export 'package:scan_me_plus/views/pages/add_vehicle_detail/choose_vehicle_type_screen.dart';
export 'package:scan_me_plus/views/pages/add_vehicle_detail/confirm_vehicle_details_screen.dart';
export 'package:scan_me_plus/views/pages/plans/upgrade_plans_screen.dart';
export 'package:scan_me_plus/views/pages/thanks_for_choosing/thanks_screen.dart';
export 'package:scan_me_plus/views/pages/shipping_address/shipping_address_screen.dart';
export 'package:scan_me_plus/views/pages/profile/edit_profile_screen.dart';
export 'package:scan_me_plus/views/pages/refer_friend/refer_friend_screen.dart';
export 'package:scan_me_plus/views/pages/about/about_screen.dart';
export 'package:scan_me_plus/views/pages/help_support/help_support_screen.dart';
export 'package:scan_me_plus/views/pages/scan_qr/scan_qr_screen.dart';
export 'package:scan_me_plus/views/pages/home/replacement_screen.dart';
export 'package:scan_me_plus/views/pages/alert_and_notifications/alert_and_notifications_screen.dart';
export 'package:scan_me_plus/views/pages/call/calling_screen.dart';
export 'package:scan_me_plus/views/pages/plans/purchase_list_screen.dart';
export 'package:scan_me_plus/views/pages/alert_and_notifications/notification_alert_screen.dart';
export 'package:scan_me_plus/views/pages/blocked_users/blocked_users_list_screen.dart';
export 'package:scan_me_plus/views/pages/static_pages/static_page_screen.dart';
export 'package:scan_me_plus/views/pages/static_pages/how_it_works_screen.dart';
export 'package:scan_me_plus/views/pages/about/society_hotel_signup_screen.dart';

// controllers
export 'package:scan_me_plus/controllers/on_boarding/on_boarding_controller.dart';
export 'package:scan_me_plus/controllers/login/login_controller.dart';
export 'package:scan_me_plus/controllers/otp_verification/otp_verification_controller.dart';
export 'package:scan_me_plus/controllers/add_profile_detail/add_profile_detail_controller.dart';
export 'package:scan_me_plus/controllers/call/call_history_controller.dart';
export 'package:scan_me_plus/controllers/home/home_controller.dart';
export 'package:scan_me_plus/controllers/home/main_controller.dart';
export 'package:scan_me_plus/controllers/plans/my_plans_controller.dart';
export 'package:scan_me_plus/controllers/profile/my_profile_controller.dart';
export 'package:scan_me_plus/controllers/add_vehicle_detail/choose_vehicle_brand_controller.dart';
export 'package:scan_me_plus/controllers/add_vehicle_detail/choose_vehicle_model_controller.dart';
export 'package:scan_me_plus/controllers/add_vehicle_detail/choose_vehicle_type_controller.dart';
export 'package:scan_me_plus/controllers/add_vehicle_detail/confirm_vehicle_details_controller.dart';
export 'package:scan_me_plus/controllers/plans/upgrade_plans_controller.dart';
export 'package:scan_me_plus/controllers/thanks_for_choosing/thanks_controller.dart';
export 'package:scan_me_plus/controllers/shipping_address/shipping_address_controller.dart';
export 'package:scan_me_plus/controllers/profile/edit_profile_controller.dart';
export 'package:scan_me_plus/controllers/refer_friend/refer_friend_controller.dart';
export 'package:scan_me_plus/controllers/help_support/help_support_controller.dart';
export 'package:scan_me_plus/controllers/about/about_controller.dart';
export 'package:scan_me_plus/controllers/scan_qr/scan_qr_controller.dart';
export 'package:scan_me_plus/controllers/home/replacement_controller.dart';
export 'package:scan_me_plus/controllers/alert_and_notifications/alert_and_notifications_controller.dart';
export 'package:scan_me_plus/controllers/call/calling_controller.dart';
export 'package:scan_me_plus/controllers/plans/purchase_list_controller.dart';
export 'package:scan_me_plus/controllers/alert_and_notifications/notification_alert_controller.dart';
export 'package:scan_me_plus/controllers/blocked_users/blocked_users_list_controller.dart';
export 'package:scan_me_plus/controllers/static_pages/static_page_controller.dart';
export 'package:scan_me_plus/controllers/about/society_hotel_signup_controller.dart';

// bindings
export 'package:scan_me_plus/bindings/on_boarding/on_boarding_binding.dart';
export 'package:scan_me_plus/bindings/login/login_binding.dart';
export 'package:scan_me_plus/bindings/otp_verification/otp_verification_binding.dart';
export 'package:scan_me_plus/bindings/add_profile_detail/add_profile_detail_binding.dart';
export 'package:scan_me_plus/bindings/home/main_binding.dart';
export 'package:scan_me_plus/bindings/add_vehicle_detail/choose_vehicle_brand_binding.dart';
export 'package:scan_me_plus/bindings/add_vehicle_detail/choose_vehicle_model_binding.dart';
export 'package:scan_me_plus/bindings/add_vehicle_detail/choose_vehicle_type_binding.dart';
export 'package:scan_me_plus/bindings/add_vehicle_detail/confirm_vehicle_details_binding.dart';
export 'package:scan_me_plus/bindings/plans/upgrade_plans_binding.dart';
export 'package:scan_me_plus/bindings/thanks_for_choosing/thanks_binding.dart';
export 'package:scan_me_plus/bindings/shipping_address/shipping_address_binding.dart';
export 'package:scan_me_plus/bindings/profile/edit_profile_binding.dart';
export 'package:scan_me_plus/bindings/refer_friend/refer_friend_binding.dart';
export 'package:scan_me_plus/bindings/about/about_binding.dart';
export 'package:scan_me_plus/bindings/help_support/help_support_binding.dart';
export 'package:scan_me_plus/bindings/scan_qr/scan_qr_binding.dart';
export 'package:scan_me_plus/bindings/home/replacement_binding.dart';
export 'package:scan_me_plus/bindings/alert_and_notifications/alert_and_notifications_binding.dart';
export 'package:scan_me_plus/bindings/call/calling_binding.dart';
export 'package:scan_me_plus/bindings/plans/my_plans_binding.dart';
export 'package:scan_me_plus/bindings/alert_and_notifications/notification_alert_binding.dart';
export 'package:scan_me_plus/bindings/blocked_users/blocked_users_list_binding.dart';
export 'package:scan_me_plus/bindings/static_pages/static_page_binding.dart';
export 'package:scan_me_plus/bindings/about/society_hotel_signup_binding.dart';
